// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

var isBrowser = typeof window !== "undefined";

function make(param) {
  if (!isBrowser || (ethereum == null)) {
    return ;
  } else {
    return Caml_option.some(ethereum);
  }
}

export {
  isBrowser ,
  make ,
  
}
/* isBrowser Not a pure module */
