// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as Eth from "../../../src/Eth.bs.js";
import * as Chain from "../../../src/Chain.bs.js";
import * as React from "react";
import * as Methods from "../../../src/Methods.bs.js";
import * as $$Promise from "reason-promise/src/js/promise.js";

function Index$default(Props) {
  var eth = Eth.make(/* () */0);
  var match = eth.status;
  if (match) {
    $$Promise.tapOk(Methods.gasPrice(/* () */0), (function (v) {
            console.log(v);
            return /* () */0;
          }));
  } else {
    console.log(Chain.toId(eth.chain));
  }
  return React.createElement("div", undefined, "hello");
}

var $$default = Index$default;

export {
  $$default ,
  $$default as default,
  
}
/* Eth Not a pure module */
