// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Error = require("../../../src/Error.bs.js");
var Hooks = require("../../../src/Hooks.bs.js");
var React = require("react");
var Caml_array = require("bs-platform/lib/js/caml_array.js");
var AccountBalance = require("../components/AccountBalance.bs.js");

function Index$default(Props) {
  var accounts = Hooks.useAccounts(/* () */0);
  var tmp;
  tmp = typeof accounts === "number" ? "Waiting" : (
      accounts.tag ? $$Error.toString(accounts[0]) : React.createElement(AccountBalance.make, {
              account: Caml_array.caml_array_get(accounts[0], 0)
            })
    );
  return React.createElement("div", undefined, tmp);
}

var $$default = Index$default;

exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Hooks Not a pure module */
