// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Error = require("../../../src/Error.bs.js");
var Ether = require("../../../src/Ether.bs.js");
var Hooks = require("../../../src/Hooks.bs.js");
var React = require("react");

function AccountBalance(Props) {
  var account = Props.account;
  var result = Hooks.useBalance(account, /* Latest */0);
  var tmp;
  tmp = typeof result === "number" ? React.createElement("p", undefined, "Requesting Balance") : (
      result.tag ? React.createElement("p", undefined, $$Error.toString(result[0])) : React.createElement("p", undefined, Ether.toStringWithUnit(Ether.convert(result[0], /* ether */-193685050)))
    );
  return React.createElement("div", undefined, tmp);
}

var make = AccountBalance;

exports.make = make;
/* Ether Not a pure module */
