// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function fromId(chainId) {
  switch (chainId) {
    case "0x0000" :
        return /* NotConnected */6;
    case "0x1" :
        return /* Mainnet */0;
    case "0x2" :
        return /* Morden */1;
    case "0x3" :
        return /* Ropsten */2;
    case "0x4" :
        return /* Rinkeby */3;
    case "0x42" :
        return /* Kovan */5;
    case "0x5" :
        return /* Goerli */4;
    default:
      return /* Other */[chainId];
  }
}

function toName(chain) {
  if (typeof chain === "number") {
    switch (chain) {
      case /* Mainnet */0 :
          return "Mainnet";
      case /* Morden */1 :
          return "Morden";
      case /* Ropsten */2 :
          return "Ropsten";
      case /* Rinkeby */3 :
          return "Rinkeby";
      case /* Goerli */4 :
          return "Goerli";
      case /* Kovan */5 :
          return "Kovan";
      case /* NotConnected */6 :
          return "Not Connected";
      
    }
  } else {
    return chain[0];
  }
}

function toId(chain) {
  if (typeof chain === "number") {
    switch (chain) {
      case /* Mainnet */0 :
          return "0x1";
      case /* Morden */1 :
          return "0x2";
      case /* Ropsten */2 :
          return "0x3";
      case /* Rinkeby */3 :
          return "0x4";
      case /* Goerli */4 :
          return "0x5";
      case /* Kovan */5 :
          return "0x42";
      case /* NotConnected */6 :
          return "0x0000";
      
    }
  } else {
    return chain[0];
  }
}

exports.fromId = fromId;
exports.toName = toName;
exports.toId = toId;
/* No side effect */
