// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE

import * as $$Promise from "reason-promise/src/js/promise.js";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";

function requestAccounts(param) {
  return $$Promise.mapOk($$Promise.Js.toResult(ethereum.send("eth_requestAccounts")), (function (res) {
                return res.result;
              }));
}

function gasPrice(param) {
  return $$Promise.mapOk($$Promise.Js.toResult(ethereum.send("eth_gasPrice")), (function (res) {
                return Caml_format.caml_int_of_string(res.result);
              }));
}

export {
  requestAccounts ,
  gasPrice ,
  
}
/* Promise Not a pure module */
